# Generated by Django 4.1.7 on 2023-03-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_zip_to_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
