# Generated by Django 4.1.7 on 2023-03-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_price_in_product_to_unit_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OredrItem',
            new_name='OrderItem',
        ),
    ]
