# Generated by Django 4.1.7 on 2023-03-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_add_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='data',
            new_name='date',
        ),
    ]
