# Generated by Django 4.1.7 on 2023-03-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_customer_membership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
