# Generated by Django 4.1.7 on 2023-03-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_order_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='placed_At',
            new_name='placed_at',
        ),
    ]
